# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.destroy_all
Cocktail.destroy_all
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "minth")
Ingredient.create(name: "Ginger beer")
Ingredient.create(name: "whisky")
Ingredient.create(name: "rhum")
Ingredient.create(name: "vodka")
Ingredient.create(name: "martini")
Ingredient.create(name: "cachaça")
Ingredient.create(name: "sugar")
Ingredient.create(name: "grapefruit")
Ingredient.create(name: "cranberries")
Ingredient.create(name: "coffee")
Ingredient.create(name: "milk")
Ingredient.create(name: "Olives")
Ingredient.create(name: "Coconut")
Ingredient.create(name: "Pineapple juice")
Ingredient.create(name: "Aperol")
Ingredient.create(name: "Prosecco")
Ingredient.create(name: "Peach puree")
Cocktail.create(name: "Mojito")
Cocktail.create(name: "Wisky Sour")
Cocktail.create(name: "Sex On The Beach")
Cocktail.create(name: "White Russian")
Cocktail.create(name: "Cosmopolitain")
Cocktail.create(name: "Dry Martini")
Cocktail.create(name: "Pinacolada")
Cocktail.create(name: "Moscow mule")
Cocktail.create(name: "Bellini")
Cocktail.create(name: "Spritz")
